# Generated by Django 5.1.4 on 2025-01-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
