# Generated by Django 5.1.4 on 2025-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0002_project_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
