# Generated by Django 5.1.4 on 2025-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0004_file_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_file_type',
            field=models.BooleanField(default=True),
        ),
    ]
