# Generated by Django 5.1.4 on 2025-01-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0005_file_is_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_initial_query', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('document_list', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_reader.project')),
            ],
        ),
    ]
