# Generated by Django 5.1.4 on 2025-01-17 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0006_changerequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 17, 17, 34, 32, 311280, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
