# Generated by Django 5.1.4 on 2025-01-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reader', '0009_plan_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
